import { FileText } from "lucide-react";
import TerminalWindow from "../components/TerminalWindow";
import PageShell from "../components/PageShell";
import PageMeta from "../components/PageMeta";
import ResourceCard from "../components/ResourceCard";
import { dialogues, poetry } from "../data/aiGallery";
import aiArtImage from "../assets/ai-art.webp";

const AIGallery = () => {
  return (
    <PageShell>
      <PageMeta
        title="AI Gallery"
        description="AI-generated dialogues, poetry, and algorithmic art."
      />
      <TerminalWindow title="ls -l ./ai-gallery" delay={0}>
        <div className="page-header">
          <h1>AI Gallery</h1>
          <p className="subtitle">
            Conversations with great mathematical minds
          </p>
        </div>

        <div className="document-content">
          <section className="document-section">
            <h3>AI-Generated Dialogues</h3>
            <p className="text-slate-200 mb-8">
              A collection of imaginative dialogues featuring historical figures
              in mathematics and computer science. These texts explore their
              foundational ideas and historical contexts.
            </p>

            <div className="grid-2">
              {dialogues.map((person) => (
                <ResourceCard
                  key={person.name}
                  title={person.name}
                  subtitle="PDF Dialogue"
                  icon={FileText}
                  tone="violet"
                  link={person.url}
                  linkText="Download"
                  isDownload
                  downloadName={`${person.name}.pdf`}
                  badge={person.lang}
                />
              ))}
            </div>
          </section>

          <section className="document-section mt-12">
            <h3>Mathematical Poetry generated by AI</h3>
            <p className="text-slate-200 mb-8">
              We asked our AI models to capture the beauty of mathematics in
              poetic form.
            </p>

            <div className="grid-2">
              {poetry.map((poem) => (
                <article key={poem.title} className="glass-card">
                  <h4 className="text-on-primary mb-4 mt-0">{poem.title}</h4>
                  <p className="text-slate-300 italic leading-8 text-[0.95rem] m-0">
                    {poem.lines.map((line) => (
                      <span key={line}>
                        {line}
                        <br />
                      </span>
                    ))}
                  </p>
                </article>
              ))}
            </div>
          </section>

          <section className="document-section mt-12">
            <h3>Algorithmic Art</h3>
            <p className="text-slate-200 mb-8">
              Visualizing the profound complexity of mathematics through
              generative algorithms.
            </p>
            <figure className="m-0 text-center bg-black/20 p-8 rounded-xl border border-white/10">
              <img
                src={aiArtImage}
                alt="AI generated mathematical art titled The Mandelbrot Dream"
                width={1024}
                height={1024}
                className="max-w-full rounded-lg mx-auto shadow-[0_4px_20px_rgba(0,0,0,0.5)]"
              />
              <figcaption className="text-muted-foreground mt-4 text-sm italic">
                &ldquo;The Mandelbrot Dream&rdquo; — Generated with AI
              </figcaption>
            </figure>
          </section>
        </div>
      </TerminalWindow>
    </PageShell>
  );
};

export default AIGallery;
